@host=http://localhost:8080
@feedId=efc923ca-a005-4c9b-b923-44f2e24b0b36

###
POST {{host}}/api/v1/inscricao HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "nome": "IFRS9",
    "url": "https://ifrs.edu.br/rss",
    "categoria": "Educacao"
}

###
POST {{host}}/api/v1/inscricao HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "nome": "BBC Notícias",
    "url": "https://feeds.bbci.co.uk/portuguese/rss.xml",
    "categoria": "noticias"
}

###
PUT {{host}}/api/v1/inscricao/{{feedId}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "nome": "BBC Notícias 2",
    "url": "https://feeds.bbci.co.uk/portuguese/rss.xml",
    "categoria": "noticias"
}

###
PUT {{host}}/api/v1/inscricao/{{feedId}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "nome": "IFRS10",
    "url": "https://ifrs.edu.br/rss",
    "categoria": "ensino-superior"
}

###
GET {{host}}/api/v1/inscricao HTTP/1.1
Accept: application/json

###
GET {{host}}/api/v1/inscricao?buscar=30 HTTP/1.1
Accept: application/json

###
GET {{host}}/api/v1/inscricao/noticias?buscar=5 HTTP/1.1
Accept: application/json

###
GET {{host}}/api/v1/inscricao/{{feedId}}/feed?pular=10&buscar=1 HTTP/1.1
Accept: application/json

###
GET {{host}}/api/v1/inscricao/{{feedId}}/feed?pular=0&buscar=100 HTTP/1.1
Accept: application/json

###
DELETE {{host}}/api/v1/inscricao/{{feedId}} HTTP/1.1
Accept: application/json
